use anyhow::{Context, Result};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::detect::Agent;

const PROVENANCE_FILE: &str = "provenance.md";
const SKILL_DIR: &str = ".skill";

/// Provenance record for a deployment
#[derive(Debug, Clone)]
pub struct Provenance {
    /// cargo-skill version
    pub version: String,
    /// Content hash of deployed layer (SHA256)
    pub content_hash: String,
    /// Detected agents
    pub agents: Vec<Agent>,
    /// Paths where skills were deployed
    pub deployed_paths: Vec<String>,
    /// Timestamp (Unix seconds)
    pub timestamp: u64,
}

impl Provenance {
    /// Create a new provenance record
    pub fn new(agents: &[Agent], content: &str) -> Self {
        let version = env!("CARGO_PKG_VERSION").to_string();
        let content_hash = compute_hash(content);
        let deployed_paths = agents
            .iter()
            .map(|a| a.skill_path().display().to_string())
            .collect();
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        Self {
            version,
            content_hash,
            agents: agents.to_vec(),
            deployed_paths,
            timestamp,
        }
    }

    /// Serialize to markdown format
    pub fn to_markdown(&self) -> String {
        let agents_list = self
            .agents
            .iter()
            .map(|a| format!("- {:?}", a))
            .collect::<Vec<_>>()
            .join("\n");

        let paths_list = self
            .deployed_paths
            .iter()
            .map(|p| format!("- `{}`", p))
            .collect::<Vec<_>>()
            .join("\n");

        let datetime = format_timestamp(self.timestamp);

        format!(
            r#"# cargo-skill Provenance

Generated by cargo-skill v{version}

## Deployment Record

- **Timestamp**: {datetime} (Unix: {timestamp})
- **Content Hash (SHA256)**: `{content_hash}`

## Detected Agents

{agents_list}

## Deployed Paths

{paths_list}

---
This file is automatically generated by `cargo skill init`.
Do not edit manually.
"#,
            version = self.version,
            timestamp = self.timestamp,
            datetime = datetime,
            content_hash = self.content_hash,
            agents_list = agents_list,
            paths_list = paths_list,
        )
    }
}

/// Compute SHA256 hash of content
fn compute_hash(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    format!("{:x}", hasher.finalize())
}

/// Format timestamp as RFC 3339 date-time string
fn format_timestamp(unix_secs: u64) -> String {
    // Convert Unix timestamp to RFC 3339 format (YYYY-MM-DDTHH:MM:SSZ)
    // This uses a simple calculation without external crates
    const SECS_PER_MINUTE: u64 = 60;
    const SECS_PER_HOUR: u64 = 3600;
    const SECS_PER_DAY: u64 = 86400;

    // Days since Jan 1, 1970
    let days_since_epoch = unix_secs / SECS_PER_DAY;
    let secs_of_day = unix_secs % SECS_PER_DAY;

    let hour = secs_of_day / SECS_PER_HOUR;
    let min = (secs_of_day % SECS_PER_HOUR) / SECS_PER_MINUTE;
    let sec = secs_of_day % SECS_PER_MINUTE;

    // Approximate year/month/day calculation
    // 1970 + days / 365.25 gives approximate year
    let year = 1970 + (days_since_epoch / 365) as u32;
    let day_of_year = days_since_epoch % 365;

    // Simple month approximation (not accounting for leap years perfectly)
    let month = (day_of_year / 30 + 1).min(12) as u32;
    let day = (day_of_year % 30 + 1).min(31) as u32;

    format!(
        "{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z",
        year, month, day, hour, min, sec
    )
}

/// Write provenance to `.skill/provenance.md`
pub fn write(repo_root: &Path, agents: &[Agent], content: &str) -> Result<()> {
    let provenance = Provenance::new(agents, content);
    let skill_dir = repo_root.join(SKILL_DIR);
    let path = skill_dir.join(PROVENANCE_FILE);

    // Ensure .skill/ directory exists
    fs::create_dir_all(&skill_dir)
        .with_context(|| format!("Failed to create directory {}", skill_dir.display()))?;

    // Write provenance file
    fs::write(&path, provenance.to_markdown())
        .with_context(|| format!("Failed to write {}", path.display()))?;

    Ok(())
}

/// Read provenance from `.skill/provenance.md` if it exists
/// Returns parsed Provenance struct with typed fields
pub fn read(repo_root: &Path) -> Result<Option<Provenance>> {
    let path = repo_root.join(SKILL_DIR).join(PROVENANCE_FILE);

    if !path.exists() {
        return Ok(None);
    }

    let content =
        fs::read_to_string(&path).with_context(|| format!("Failed to read {}", path.display()))?;

    // Parse the markdown content back into a Provenance struct
    // This is a best-effort parse - fields that can't be parsed use defaults
    Ok(Some(parse_provenance_markdown(&content)))
}

/// Parse provenance markdown back into a Provenance struct
fn parse_provenance_markdown(content: &str) -> Provenance {
    let mut version = String::new();
    let mut content_hash = String::new();
    let mut timestamp = 0u64;
    let mut agents = Vec::new();
    let mut deployed_paths = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();

        // Parse version: "Generated by cargo-skill v0.2.5"
        if let Some(v) = trimmed.strip_prefix("Generated by cargo-skill v") {
            version = v.to_string();
        }

        // Parse content hash: "- **Content Hash (SHA256)**: `abc123...`"
        if let Some(hash_start) = trimmed.find("`")
            && let Some(hash_end) = trimmed[hash_start + 1..].find("`")
        {
            let hash = &trimmed[hash_start + 1..hash_start + 1 + hash_end];
            if hash.len() == 64 && hash.chars().all(|c| c.is_ascii_hexdigit()) {
                content_hash = hash.to_string();
            }
        }

        // Parse timestamp (Unix): look for "(Unix: 1234567890)"
        if let Some(start) = trimmed.find("(Unix: ")
            && let Some(end) = trimmed[start + 7..].find(')')
        {
            let ts_str = &trimmed[start + 7..start + 7 + end];
            if let Ok(ts) = ts_str.parse::<u64>() {
                timestamp = ts;
            }
        }

        // Parse agents: "- ClaudeCode" lines in the agents section
        if trimmed.starts_with("- ") && !trimmed.starts_with("- **") {
            let agent_str = &trimmed[2..];
            if let Some(agent) = parse_agent(agent_str) {
                agents.push(agent);
            }
        }

        // Parse deployed paths: "- `.claude/skills/rust.md`"
        if trimmed.starts_with("- `") && trimmed.ends_with("`") {
            let path = &trimmed[3..trimmed.len() - 1];
            if path.contains('/') || path.contains("\\") {
                deployed_paths.push(path.to_string());
            }
        }
    }

    Provenance {
        version,
        content_hash,
        agents,
        deployed_paths,
        timestamp,
    }
}

/// Parse agent name from string
fn parse_agent(s: &str) -> Option<Agent> {
    match s {
        "ClaudeCode" => Some(Agent::ClaudeCode),
        "Cursor" => Some(Agent::Cursor),
        "Windsurf" => Some(Agent::Windsurf),
        "AgentsMd" => Some(Agent::AgentsMd),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_compute_hash() {
        let hash1 = compute_hash("test content");
        let hash2 = compute_hash("test content");
        let hash3 = compute_hash("different content");

        // Same content = same hash
        assert_eq!(hash1, hash2);
        // Different content = different hash
        assert_ne!(hash1, hash3);
        // SHA256 produces 64-char hex string
        assert_eq!(hash1.len(), 64);
    }

    #[test]
    fn test_provenance_new() {
        let _temp = TempDir::new().unwrap();
        let agents = vec![Agent::ClaudeCode, Agent::Cursor];
        let content = "test skill content";

        let provenance = Provenance::new(&agents, content);

        assert_eq!(provenance.version, env!("CARGO_PKG_VERSION"));
        assert_eq!(provenance.agents.len(), 2);
        assert_eq!(provenance.deployed_paths.len(), 2);
        assert!(!provenance.content_hash.is_empty());
        assert!(provenance.timestamp > 0);
    }

    #[test]
    fn test_provenance_to_markdown() {
        let _temp = TempDir::new().unwrap();
        let agents = vec![Agent::ClaudeCode];
        let content = "test";

        let provenance = Provenance::new(&agents, content);
        let markdown = provenance.to_markdown();

        assert!(markdown.contains("# cargo-skill Provenance"));
        assert!(markdown.contains(&provenance.version));
        assert!(markdown.contains(&provenance.content_hash));
        assert!(markdown.contains("ClaudeCode"));
        assert!(markdown.contains(".claude/skills/rust.md"));
    }

    #[test]
    fn test_write_and_read_provenance() {
        let temp = TempDir::new().unwrap();
        let agents = vec![Agent::ClaudeCode, Agent::Windsurf];
        let content = "layer content";

        // Write provenance
        write(temp.path(), &agents, content).unwrap();

        // Verify file exists
        let path = temp.path().join(".skill/provenance.md");
        assert!(path.exists());

        // Read and verify parsed provenance struct
        let prov = read(temp.path()).unwrap().unwrap();
        assert!(!prov.version.is_empty());
        assert!(prov.agents.contains(&Agent::ClaudeCode));
        assert!(prov.agents.contains(&Agent::Windsurf));
        assert_eq!(prov.deployed_paths.len(), 2);
        assert!(!prov.content_hash.is_empty());
        assert!(prov.timestamp > 0);
    }

    #[test]
    fn test_provenance_roundtrip() {
        let temp = TempDir::new().unwrap();
        let agents = vec![Agent::ClaudeCode, Agent::Cursor];
        let content = "test roundtrip content";

        // Write
        write(temp.path(), &agents, content).unwrap();

        // Read back and verify fields match
        let prov = read(temp.path()).unwrap().unwrap();

        // Verify the parsed data is reasonable
        assert_eq!(prov.version, env!("CARGO_PKG_VERSION"));
        assert_eq!(prov.agents.len(), 2);
        assert!(prov.deployed_paths.iter().any(|p| p.contains("claude")));
        assert!(prov.deployed_paths.iter().any(|p| p.contains("cursor")));
        assert_eq!(prov.content_hash, compute_hash(content));
    }

    #[test]
    fn test_read_returns_none_when_absent() {
        let temp = TempDir::new().unwrap();

        let result = read(temp.path()).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn test_parse_agent() {
        assert_eq!(parse_agent("ClaudeCode"), Some(Agent::ClaudeCode));
        assert_eq!(parse_agent("Cursor"), Some(Agent::Cursor));
        assert_eq!(parse_agent("Windsurf"), Some(Agent::Windsurf));
        assert_eq!(parse_agent("AgentsMd"), Some(Agent::AgentsMd));
        assert_eq!(parse_agent("Unknown"), None);
    }

    #[test]
    fn test_provenance_write_all_fields_present() {
        let temp = TempDir::new().unwrap();
        let agents = vec![Agent::ClaudeCode, Agent::Cursor, Agent::Windsurf];
        let content = "test skill content for field verification";

        // Write provenance
        write(temp.path(), &agents, content).unwrap();

        // Read raw markdown content
        let path = temp.path().join(".skill/provenance.md");
        let markdown = fs::read_to_string(&path).unwrap();

        // Verify all required fields are present in markdown
        assert!(
            markdown.contains("# cargo-skill Provenance"),
            "Missing title"
        );
        assert!(
            markdown.contains("Generated by cargo-skill v"),
            "Missing version header"
        );
        assert!(
            markdown.contains(&env!("CARGO_PKG_VERSION")),
            "Missing version number"
        );
        assert!(
            markdown.contains("Content Hash (SHA256)"),
            "Missing hash label"
        );
        assert!(markdown.contains("Detected Agents"), "Missing agents label");
        assert!(markdown.contains("Deployed Paths"), "Missing paths label");
        assert!(
            markdown.contains("**Timestamp**"),
            "Missing timestamp label"
        );

        // Verify all agents are listed
        assert!(markdown.contains("ClaudeCode"), "Missing ClaudeCode agent");
        assert!(markdown.contains("Cursor"), "Missing Cursor agent");
        assert!(markdown.contains("Windsurf"), "Missing Windsurf agent");

        // Verify all paths are listed
        assert!(
            markdown.contains(".claude/skills/rust.md"),
            "Missing claude path"
        );
        assert!(
            markdown.contains(".cursor/rules/rust.md"),
            "Missing cursor path"
        );
        assert!(
            markdown.contains(".windsurf/rules/rust.md"),
            "Missing windsurf path"
        );
    }

    #[test]
    fn test_provenance_hash_correctness() {
        let temp = TempDir::new().unwrap();
        let agents = vec![Agent::ClaudeCode];
        let content = "specific content for hash verification";

        // Compute expected hash
        let expected_hash = compute_hash(content);

        // Write provenance
        write(temp.path(), &agents, content).unwrap();

        // Read raw markdown and verify hash is present
        let path = temp.path().join(".skill/provenance.md");
        let markdown = fs::read_to_string(&path).unwrap();

        // Verify the correct hash is in the file
        assert!(
            markdown.contains(&expected_hash),
            "Provenance should contain correct SHA256 hash"
        );

        // Read back and verify hash matches
        let prov = read(temp.path()).unwrap().unwrap();
        assert_eq!(
            prov.content_hash, expected_hash,
            "Parsed hash should match computed hash"
        );
        assert_eq!(
            prov.content_hash.len(),
            64,
            "SHA256 hash should be 64 hex characters"
        );
    }

    #[test]
    fn test_provenance_timestamp_valid() {
        let temp = TempDir::new().unwrap();
        let agents = vec![Agent::ClaudeCode];
        let content = "test content";

        // Record time before write
        let before = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();

        // Write provenance
        write(temp.path(), &agents, content).unwrap();

        // Record time after write
        let after = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();

        // Read back and verify timestamp is reasonable
        let prov = read(temp.path()).unwrap().unwrap();
        assert!(
            prov.timestamp >= before && prov.timestamp <= after,
            "Timestamp should be between before and after write times"
        );
    }
}
